Colorize /etc/init.d daemon outputs, log to kmsg

diff --git a/platform/rootfs_overlay/etc/init.d/S10mdev b/platform/rootfs_overlay/etc/init.d/S10mdev
--- a/platform/rootfs_overlay/etc/init.d/S10mdev
+++ b/platform/rootfs_overlay/etc/init.d/S10mdev
@@ -3,14 +3,22 @@
 # Start mdev....
 #
 
+LIGHTBLUE="\e[38;5;87m"
+LIGHTGREEN="\e[38;5;46m"
+LIGHTRED="\e[38;5;196m"
+NORMAL="\e[0m"
+OK="${LIGHTGREEN}OK${NORMAL}"
+FAIL="${LIGHTRED}FAIL${NORMAL}"
+HEADER="${LIGHTBLUE}[S10 mdev]${NORMAL}\t"
+
 case "$1" in
   start)
-	echo -n "Starting mdev: "
+	echo -ne "${HEADER}Starting mdev..." > /dev/kmsg
 	echo /sbin/mdev >/proc/sys/kernel/hotplug
 	/sbin/mdev -s
 	# coldplug modules
 	# find /sys/ -name modalias -print0 | xargs -0 sort -u -z | xargs -0 modprobe -abq
-	[ $? = 0 ] && echo "OK" || echo "FAIL"
+	[ $? = 0 ] && echo -e "${HEADER}${OK}" > /dev/kmsg || echo "${HEADER}${FAIL}" > /dev/kmsg
 	;;
   stop)
 	;;
diff --git a/platform/rootfs_overlay/etc/init.d/S15watchdog b/platform/rootfs_overlay/etc/init.d/S15watchdog
--- a/platform/rootfs_overlay/etc/init.d/S15watchdog
+++ b/platform/rootfs_overlay/etc/init.d/S15watchdog
@@ -3,11 +3,19 @@
 # Start watchdog
 #
 
+LIGHTBLUE="\e[38;5;87m"
+LIGHTGREEN="\e[38;5;46m"
+LIGHTRED="\e[38;5;196m"
+NORMAL="\e[0m"
+OK="${LIGHTGREEN}OK${NORMAL}"
+FAIL="${LIGHTRED}FAIL${NORMAL}"
+HEADER="${LIGHTBLUE}[S15 watchdog]${NORMAL}\t"
+
 case "$1" in
  start)
-	echo -n "Starting watchdog: "
+	echo -ne "${HEADER}Starting watchdog..." > /dev/kmsg
 	watchdog -t 5 -T 10 /dev/watchdog
-	[ $? = 0 ] && echo "OK" || echo "FAIL"
+	[ $? = 0 ] && echo -e "${HEADER}${OK}"  > /dev/kmsg || echo "${HEADER}${FAIL}" > /dev/kmsg
 	;;
   stop)
 	;;
diff --git a/platform/rootfs_overlay/etc/init.d/S20urandom b/platform/rootfs_overlay/etc/init.d/S20urandom
--- a/platform/rootfs_overlay/etc/init.d/S20urandom
+++ b/platform/rootfs_overlay/etc/init.d/S20urandom
@@ -1,4 +1,4 @@
-#! /bin/sh
+#!/bin/sh
 #
 # urandom	This script saves the random seed between reboots.
 #		It is called from the boot, halt and reboot scripts.
@@ -6,18 +6,26 @@
 # Version:	@(#)urandom  1.33  22-Jun-1998  miquels@cistron.nl
 #
 
+LIGHTBLUE="\e[38;5;87m"
+LIGHTGREEN="\e[38;5;46m"
+LIGHTRED="\e[38;5;196m"
+NORMAL="\e[0m"
+OK="${LIGHTGREEN}OK${NORMAL}"
+FAIL="${LIGHTRED}FAIL${NORMAL}"
+HEADER="${LIGHTBLUE}[S20 urandom]${NORMAL}\t"
+
 [ -c /dev/urandom ] || exit 0
 #. /etc/default/rcS
 
 case "$1" in
 	start|"")
-		echo -n "Starting initializing random number generator: "
+		echo -ne "${HEADER}Starting initializing random number generator..."  > /dev/kmsg
 
 		# Load and then save 512 bytes,
 		# which is the size of the entropy pool
 
 		dmesg | sha512sum > /dev/urandom
-		[ $? = 0 ] && echo "OK" || echo "FAIL"
+		[ $? = 0 ] && echo -e "${HEADER}${OK}" > /dev/kmsg || echo "${HEADER}${FAIL}" > /dev/kmsg
 		;;
 	stop)
 
diff --git a/platform/rootfs_overlay/etc/init.d/S21misc b/platform/rootfs_overlay/etc/init.d/S21misc
--- a/platform/rootfs_overlay/etc/init.d/S21misc
+++ b/platform/rootfs_overlay/etc/init.d/S21misc
@@ -1,4 +1,12 @@
-#! /bin/sh
+#!/bin/sh
+
+LIGHTBLUE="\e[38;5;87m"
+LIGHTGREEN="\e[38;5;46m"
+LIGHTRED="\e[38;5;196m"
+NORMAL="\e[0m"
+OK="${LIGHTGREEN}OK${NORMAL}"
+FAIL="${LIGHTRED}FAIL${NORMAL}"
+HEADER="${LIGHTBLUE}[S21 misc]${NORMAL}\t"
 
 xo_correction() {
 
@@ -16,11 +24,11 @@ xo_correction() {
 
 case "$1" in
 	start|"")
-		echo -n "Starting miscellaneous setup: "
+		echo -ne "${HEADER}Starting miscellaneous setup..." > /dev/kmsg
 		xo_correction
 		MAX_BS=`fw_printenv -n iio_max_block_size 2> /dev/null || echo 67108864`
 		echo ${MAX_BS} > /sys/module/industrialio_buffer_dma/parameters/max_block_size
-		[ $? = 0 ] && echo "OK" || echo "FAIL"
+		[ $? = 0 ] && echo -e "${HEADER}${OK}" > /dev/kmsg || echo "${HEADER}${FAIL}" > /dev/kmsg
 		;;
 	stop)
 
diff --git a/platform/rootfs_overlay/etc/init.d/S23udc b/platform/rootfs_overlay/etc/init.d/S23udc
--- a/platform/rootfs_overlay/etc/init.d/S23udc
+++ b/platform/rootfs_overlay/etc/init.d/S23udc
@@ -1,5 +1,13 @@
 #!/bin/sh
 
+LIGHTBLUE="\e[38;5;87m"
+LIGHTGREEN="\e[38;5;46m"
+LIGHTRED="\e[38;5;196m"
+NORMAL="\e[0m"
+OK="${LIGHTGREEN}OK${NORMAL}"
+FAIL="${LIGHTRED}FAIL${NORMAL}"
+HEADER="${LIGHTBLUE}[S23 udc]${NORMAL}\t"
+
 source /etc/device_config
 
 CONFIGFS=/sys/kernel/config/usb_gadget
@@ -48,7 +56,7 @@ create_iiod_context_attributes() {
 
 case "$1" in
   start)
-	echo -n "Starting UDC Gadgets: "
+	echo -ne "${HEADER}Starting UDC Gadgets..." > /dev/kmsg
 	mount configfs -t configfs /sys/kernel/config 2> /dev/null
 
 	mkdir -p $GADGET
@@ -104,7 +112,7 @@ case "$1" in
 
 	echo ci_hdrc.0 > $GADGET/UDC
 
-	[ $? = 0 ] && echo "OK" || echo "FAIL"
+	[ $? = 0 ] && echo -e "${HEADER}${OK}" || echo "${HEADER}${FAIL}"
 
 	if [ "$UDC_HANDLE_SUSPEND" == "1" ]; then
 		start-stop-daemon -S -b -q -m -p /var/run/udc_handle_suspend.pid -x  /sbin/udc_handle_suspend.sh
@@ -112,7 +120,7 @@ case "$1" in
 
 	;;
   stop)
-	echo "Stopping UDC Gadgets"
+	echo -ne "${HEADER}Stopping UDC Gadgets" > /dev/kmsg
 
 	if [ "$UDC_HANDLE_SUSPEND" == "1" ]; then
 		start-stop-daemon -K -q -p /var/run/udc_handle_suspend.pid 2>/dev/null
diff --git a/platform/rootfs_overlay/etc/init.d/S40network b/platform/rootfs_overlay/etc/init.d/S40network
--- a/platform/rootfs_overlay/etc/init.d/S40network
+++ b/platform/rootfs_overlay/etc/init.d/S40network
@@ -5,6 +5,14 @@
 
 # Debian ifupdown needs the /run/network lock directory
 
+LIGHTBLUE="\e[38;5;87m"
+LIGHTGREEN="\e[38;5;46m"
+LIGHTRED="\e[38;5;196m"
+NORMAL="\e[0m"
+OK="${LIGHTGREEN}OK${NORMAL}"
+FAIL="${LIGHTRED}FAIL${NORMAL}"
+HEADER="${LIGHTBLUE}[S40 network]${NORMAL}\t"
+
 source /etc/device_config
 
 create_system_files () {
@@ -121,15 +129,15 @@ mkdir -p /run/network
 case "$1" in
   start)
 	create_system_files
-	printf "Starting network: "
+	echo -ne "${HEADER}Starting network..." > /dev/kmsg
 	/bin/hostname -F /etc/hostname
 	/sbin/ifup -a 2>&1 | logger
-	[ $? = 0 ] && echo "OK" || echo "FAIL"
+	[ $? = 0 ] && echo -e "${HEADER}${OK}" || echo "${HEADER}${FAIL}"
 	;;
   stop)
-	printf "Stopping network: "
+	echo -ne "${HEADER}Stopping network..." > /dev/kmsg
 	/sbin/ifdown -a
-	[ $? = 0 ] && echo "OK" || echo "FAIL"
+	[ $? = 0 ] && echo -e "${HEADER}${OK}" || echo "${HEADER}${FAIL}"
 	;;
   restart|reload)
 	"$0" stop
diff --git a/platform/rootfs_overlay/etc/init.d/S41network b/platform/rootfs_overlay/etc/init.d/S41network
--- a/platform/rootfs_overlay/etc/init.d/S41network
+++ b/platform/rootfs_overlay/etc/init.d/S41network
@@ -1,21 +1,29 @@
 #!/bin/sh
 # Server-side demuxing by default
 
+LIGHTBLUE="\e[38;5;87m"
+LIGHTGREEN="\e[38;5;46m"
+LIGHTRED="\e[38;5;196m"
+NORMAL="\e[0m"
+OK="${LIGHTGREEN}OK${NORMAL}"
+FAIL="${LIGHTRED}FAIL${NORMAL}"
+HEADER="${LIGHTBLUE}[S41 udhcpd]${NORMAL}\t"
+
 source /etc/device_config
 
 case "$1" in
 	start)
-		echo -n "Starting dhcpd Daemon & httpd Server: "
+		echo -ne "${HEADER}Starting dhcpd Daemon & httpd Server..." > /dev/kmsg
 		start-stop-daemon -S -b -q -m -p /var/run/udhcpd.pid -x /usr/sbin/udhcpd -- $UDHCPD_CONF
 		httpd -h /www
-		[ $? = 0 ] && echo "OK" || echo "FAIL"
+		[ $? = 0 ] && echo -e "${HEADER}${OK}" || echo "${HEADER}${FAIL}"
 		;;
 
 	stop)
-		echo -n "Stopping dhcpd Daemon & httpd Server: "
+		echo -ne "${HEADER}Stopping dhcpd Daemon & httpd Server..." > /dev/kmsg
 		killall -7 httpd
 		start-stop-daemon -K -q -p /var/run/udhcpd.pid 2>/dev/null
-		[ $? = 0 ] && echo "OK" || echo "FAIL"
+		[ $? = 0 ] && echo -e "${HEADER}${OK}" || echo "${HEADER}${FAIL}"
 		;;
 
 	restart)
diff --git a/platform/rootfs_overlay/etc/init.d/S45msd b/platform/rootfs_overlay/etc/init.d/S45msd
--- a/platform/rootfs_overlay/etc/init.d/S45msd
+++ b/platform/rootfs_overlay/etc/init.d/S45msd
@@ -1,6 +1,14 @@
 #!/bin/sh
 # Server-side demuxing by default
 
+LIGHTBLUE="\e[38;5;87m"
+LIGHTGREEN="\e[38;5;46m"
+LIGHTRED="\e[38;5;196m"
+NORMAL="\e[0m"
+OK="${LIGHTGREEN}OK${NORMAL}"
+FAIL="${LIGHTRED}FAIL${NORMAL}"
+HEADER="${LIGHTBLUE}[S45 msd]${NORMAL}\t"
+
 source /etc/device_config
 
 CONF=/opt/config.txt
@@ -27,7 +35,7 @@ patch_html_page() {
 
 case "$1" in
 	start)
-		echo -n "Starting MSD Daemon: "
+		echo -ne "${HEADER}Starting MSD Daemon..." > /dev/kmsg
 		patch_html_page "/www/index.html /www/img/index_*.html" /www/img/version.js
         dd if=/dev/zero of=$img bs=1M seek=30 count=0
         mkfs.vfat -n PlutoSDR $img
@@ -48,13 +56,13 @@ case "$1" in
 		echo $img > $file
 
 		start-stop-daemon -S -b -q -m -p /var/run/update.pid -x /bin/sh -- /sbin/update.sh
-		[ $? = 0 ] && echo "OK" || echo "FAIL"
+		[ $? = 0 ] && echo -e "${HEADER}${OK}" || echo "${HEADER}${FAIL}"
 		;;
 
 	stop)
-		echo -n "Stopping MSD Daemon: "
+		echo -ne "${HEADER}Stopping MSD Daemon..." > /dev/kmsg
 		start-stop-daemon -K -q -p /var/run/update.pid 2>/dev/null
-		[ $? = 0 ] && echo "OK" || echo "FAIL"
+		[ $? = 0 ] && echo -e "${HEADER}${OK}" || echo "${HEADER}${FAIL}"
 		;;
 
 	restart)
diff --git a/platform/rootfs_overlay/etc/init.d/S46axidma b/platform/rootfs_overlay/etc/init.d/S46axidma
--- a/platform/rootfs_overlay/etc/init.d/S46axidma
+++ b/platform/rootfs_overlay/etc/init.d/S46axidma
@@ -1,12 +1,24 @@
 #!/bin/sh
 
+LIGHTBLUE="\e[38;5;87m"
+LIGHTGREEN="\e[38;5;46m"
+LIGHTRED="\e[38;5;196m"
+NORMAL="\e[0m"
+OK="${LIGHTGREEN}OK${NORMAL}"
+FAIL="${LIGHTRED}FAIL${NORMAL}"
+HEADER="${LIGHTBLUE}[S46 axidma]${NORMAL}\t"
+
 case "$1" in
 	start)
+		echo -ne "${HEADER}Loading axidma kernel module..." > /dev/kmsg
 		modprobe axidma
+		[ $? = 0 ] && echo -e "${HEADER}${OK}" || echo "${HEADER}${FAIL}"
 		;;
 
 	stop)
+		echo -ne "${HEADER}Unloading axidma kernel module..." > /dev/kmsg
 		rmmod axidma
+		[ $? = 0 ] && echo -e "${HEADER}${OK}" || echo "${HEADER}${FAIL}"
 		;;
 
 	restart)
