Fix init daemon echo OK status to kmsg

diff --git a/platform/rootfs_overlay/etc/init.d/S20urandom b/platform/rootfs_overlay/etc/init.d/S20urandom
--- a/platform/rootfs_overlay/etc/init.d/S20urandom
+++ b/platform/rootfs_overlay/etc/init.d/S20urandom
@@ -19,13 +19,13 @@ HEADER="${LIGHTBLUE}[S20 urandom]${NORMAL}\t"
 
 case "$1" in
 	start|"")
-		echo -ne "${HEADER}Starting initializing random number generator..."  > /dev/kmsg
+		echo -ne "${HEADER}Starting initializing random number generator..." > /dev/kmsg
 
 		# Load and then save 512 bytes,
 		# which is the size of the entropy pool
 
 		dmesg | sha512sum > /dev/urandom
-		[ $? = 0 ] && echo -e "${HEADER}started ${OK}" || echo -e "${HEADER}start ${FAIL}" > /dev/kmsg
+		[ $? = 0 ] && echo -e "${HEADER}started ${OK}" > /dev/kmsg || echo -e "${HEADER}start ${FAIL}" > /dev/kmsg
 		;;
 	stop)
 		;;
diff --git a/platform/rootfs_overlay/etc/init.d/S40network b/platform/rootfs_overlay/etc/init.d/S40network
--- a/platform/rootfs_overlay/etc/init.d/S40network
+++ b/platform/rootfs_overlay/etc/init.d/S40network
@@ -98,12 +98,12 @@ case "$1" in
 	echo -e "${HEADER}Starting network..." > /dev/kmsg
 	/bin/hostname -F /etc/hostname
 	/sbin/ifup -a 2>&1 | logger
-	[ $? = 0 ] && echo -e "${HEADER}started ${OK}" || echo -e "${HEADER}start ${FAIL}" > /dev/kmsg
+	[ $? = 0 ] && echo -e "${HEADER}started ${OK}" > /dev/kmsg || echo -e "${HEADER}start ${FAIL}" > /dev/kmsg
 	;;
   stop)
 	echo -e "${HEADER}Stopping network..." > /dev/kmsg
 	/sbin/ifdown -a
-	[ $? = 0 ] && echo -e "${HEADER}stopped ${OK}" || echo -e "${HEADER}stop ${FAIL}" > /dev/kmsg
+	[ $? = 0 ] && echo -e "${HEADER}stopped ${OK}" > /dev/kmsg || echo -e "${HEADER}stop ${FAIL}" > /dev/kmsg
 	;;
   restart|reload)
 	"$0" stop
