Move verbose init start/stop messages

diff --git a/platform/rootfs_overlay/etc/init.d/S21misc b/platform/rootfs_overlay/etc/init.d/S21misc
--- a/platform/rootfs_overlay/etc/init.d/S21misc
+++ b/platform/rootfs_overlay/etc/init.d/S21misc
@@ -28,10 +28,9 @@ case "$1" in
 		xo_correction
 		MAX_BS=`fw_printenv -n iio_max_block_size 2> /dev/null || echo 67108864`
 		echo ${MAX_BS} > /sys/module/industrialio_buffer_dma/parameters/max_block_size
-		[ $? = 0 ] && echo -e "${HEADER}${OK}" > /dev/kmsg || echo -e "${HEADER}${FAIL}" > /dev/kmsg
+		[ $? = 0 ] && echo -e "${HEADER}started ${OK}" || echo -e "${HEADER}start ${FAIL}" > /dev/kmsg
 		;;
 	stop)
-
 		;;
 	*)
 		echo "Usage: $0 {start|stop}" >&2
diff --git a/platform/rootfs_overlay/etc/init.d/S23udc b/platform/rootfs_overlay/etc/init.d/S23udc
--- a/platform/rootfs_overlay/etc/init.d/S23udc
+++ b/platform/rootfs_overlay/etc/init.d/S23udc
@@ -112,7 +112,7 @@ case "$1" in
 
 	echo ci_hdrc.0 > $GADGET/UDC
 
-	[ $? = 0 ] && echo -e "${HEADER}${OK}" || echo "${HEADER}${FAIL}" > /dev/kmsg
+	[ $? = 0 ] && echo -e "${HEADER}started ${OK}" || echo -e "${HEADER}start ${FAIL}" > /dev/kmsg
 
 	if [ "$UDC_HANDLE_SUSPEND" == "1" ]; then
 		start-stop-daemon -S -b -q -m -p /var/run/udc_handle_suspend.pid -x  /sbin/udc_handle_suspend.sh
@@ -145,7 +145,7 @@ case "$1" in
 
 	rmdir $GADGET 2> /dev/null
 
-	[ $? = 0 ] && echo -e "${HEADER}${OK}" || echo -e "${HEADER}${FAIL}" > /dev/kmsg
+	[ $? = 0 ] && echo -e "${HEADER}stopped ${OK}" || echo -e "${HEADER}stop ${FAIL}" > /dev/kmsg
 	;;
   restart|reload)
 	"$0" stop
diff --git a/platform/rootfs_overlay/etc/init.d/S46axidma b/platform/rootfs_overlay/etc/init.d/S46axidma
--- a/platform/rootfs_overlay/etc/init.d/S46axidma
+++ b/platform/rootfs_overlay/etc/init.d/S46axidma
@@ -12,13 +12,13 @@ case "$1" in
 	start)
 		echo -ne "${HEADER}Loading axidma kernel module..." > /dev/kmsg
 		modprobe axidma
-		[ $? = 0 ] && echo -e "${HEADER}${OK}" || echo -e "${HEADER}${FAIL}" > /dev/kmsg
+		[ $? = 0 ] && echo -e "${HEADER}started ${OK}" || echo -e "${HEADER}start ${FAIL}" > /dev/kmsg
 		;;
 
 	stop)
 		echo -ne "${HEADER}Unloading axidma kernel module..." > /dev/kmsg
 		rmmod axidma
-		[ $? = 0 ] && echo -e "${HEADER}${OK}" || echo -e "${HEADER}${FAIL}" > /dev/kmsg
+		[ $? = 0 ] && echo -e "${HEADER}stopped ${OK}" || echo -e "${HEADER}stop ${FAIL}" > /dev/kmsg
 		;;
 
 	restart)
