Fixes for /etc/init.d daemon outputs

diff --git a/platform/rootfs_overlay/etc/init.d/S40network b/platform/rootfs_overlay/etc/init.d/S40network
--- a/platform/rootfs_overlay/etc/init.d/S40network
+++ b/platform/rootfs_overlay/etc/init.d/S40network
@@ -132,12 +132,12 @@ case "$1" in
 	echo -ne "${HEADER}Starting network..." > /dev/kmsg
 	/bin/hostname -F /etc/hostname
 	/sbin/ifup -a 2>&1 | logger
-	[ $? = 0 ] && echo -e "${HEADER}${OK}" || echo "${HEADER}${FAIL}"
+	[ $? = 0 ] && echo -e "${HEADER}${OK}" || echo -e "${HEADER}${FAIL}" > /dev/kmsg
 	;;
   stop)
 	echo -ne "${HEADER}Stopping network..." > /dev/kmsg
 	/sbin/ifdown -a
-	[ $? = 0 ] && echo -e "${HEADER}${OK}" || echo "${HEADER}${FAIL}"
+	[ $? = 0 ] && echo -e "${HEADER}${OK}" || echo -e "${HEADER}${FAIL}" > /dev/kmsg
 	;;
   restart|reload)
 	"$0" stop
diff --git a/platform/rootfs_overlay/etc/init.d/S41network b/platform/rootfs_overlay/etc/init.d/S41network
--- a/platform/rootfs_overlay/etc/init.d/S41network
+++ b/platform/rootfs_overlay/etc/init.d/S41network
@@ -16,14 +16,14 @@ case "$1" in
 		echo -ne "${HEADER}Starting dhcpd Daemon & httpd Server..." > /dev/kmsg
 		start-stop-daemon -S -b -q -m -p /var/run/udhcpd.pid -x /usr/sbin/udhcpd -- $UDHCPD_CONF
 		httpd -h /www
-		[ $? = 0 ] && echo -e "${HEADER}${OK}" || echo "${HEADER}${FAIL}"
+		[ $? = 0 ] && echo -e "${HEADER}${OK}" || echo -e "${HEADER}${FAIL}" > /dev/kmsg
 		;;
 
 	stop)
 		echo -ne "${HEADER}Stopping dhcpd Daemon & httpd Server..." > /dev/kmsg
 		killall -7 httpd
 		start-stop-daemon -K -q -p /var/run/udhcpd.pid 2>/dev/null
-		[ $? = 0 ] && echo -e "${HEADER}${OK}" || echo "${HEADER}${FAIL}"
+		[ $? = 0 ] && echo -e "${HEADER}${OK}" || echo -e "${HEADER}${FAIL}" > /dev/kmsg
 		;;
 
 	restart)
diff --git a/platform/rootfs_overlay/etc/init.d/S45msd b/platform/rootfs_overlay/etc/init.d/S45msd
--- a/platform/rootfs_overlay/etc/init.d/S45msd
+++ b/platform/rootfs_overlay/etc/init.d/S45msd
@@ -56,13 +56,13 @@ case "$1" in
 		echo $img > $file
 
 		start-stop-daemon -S -b -q -m -p /var/run/update.pid -x /bin/sh -- /sbin/update.sh
-		[ $? = 0 ] && echo -e "${HEADER}${OK}" || echo "${HEADER}${FAIL}"
+		[ $? = 0 ] && echo -e "${HEADER}${OK}" || echo -e "${HEADER}${FAIL}" > /dev/kmsg
 		;;
 
 	stop)
 		echo -ne "${HEADER}Stopping MSD Daemon..." > /dev/kmsg
 		start-stop-daemon -K -q -p /var/run/update.pid 2>/dev/null
-		[ $? = 0 ] && echo -e "${HEADER}${OK}" || echo "${HEADER}${FAIL}"
+		[ $? = 0 ] && echo -e "${HEADER}${OK}" || echo -e "${HEADER}${FAIL}" > /dev/kmsg
 		;;
 
 	restart)
